//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLS.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btn_add {
            get {
                return ResourceManager.GetString("btn_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btn_delete {
            get {
                return ResourceManager.GetString("btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btn_find {
            get {
                return ResourceManager.GetString("btn_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자관리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Btn_Master_User {
            get {
                return ResourceManager.GetString("Btn_Master_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   납품처리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Btn_SD_Delivery {
            get {
                return ResourceManager.GetString("Btn_SD_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string display_kor_name {
            get {
                return ResourceManager.GetString("display_kor_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap img_find {
            get {
                object obj = ResourceManager.GetObject("img_find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   성명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lbl_name {
            get {
                return ResourceManager.GetString("lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lbl_userID {
            get {
                return ResourceManager.GetString("lbl_userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Login_Form {
            get {
                object obj = ResourceManager.GetObject("Login_Form", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap loginBTN {
            get {
                object obj = ResourceManager.GetObject("loginBTN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   사용자관리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Master_G1 {
            get {
                return ResourceManager.GetString("Master_G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디또는 비밀번호를 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_001 {
            get {
                return ResourceManager.GetString("msg_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 아이디가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_002 {
            get {
                return ResourceManager.GetString("msg_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호가 일치하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_003 {
            get {
                return ResourceManager.GetString("msg_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리스트에서 삭제할 사용자를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_004 {
            get {
                return ResourceManager.GetString("msg_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_005 {
            get {
                return ResourceManager.GetString("msg_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string person_id {
            get {
                return ResourceManager.GetString("person_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   직급과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string pstn_name_kor {
            get {
                return ResourceManager.GetString("pstn_name_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Rbn_Menu_Home {
            get {
                return ResourceManager.GetString("Rbn_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기준정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Rbn_Menu_Master {
            get {
                return ResourceManager.GetString("Rbn_Menu_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자재과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Rbn_Menu_MM {
            get {
                return ResourceManager.GetString("Rbn_Menu_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생산과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Rbn_Menu_PP {
            get {
                return ResourceManager.GetString("Rbn_Menu_PP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영업과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Rbn_Menu_SD {
            get {
                return ResourceManager.GetString("Rbn_Menu_SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   납품과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SD_G1 {
            get {
                return ResourceManager.GetString("SD_G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부서명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string unit_name_kor {
            get {
                return ResourceManager.GetString("unit_name_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string User_Management {
            get {
                return ResourceManager.GetString("User_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap window_menu {
            get {
                object obj = ResourceManager.GetObject("window_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
